theme = "monokai"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

# [editor.whitespace]
# render = "all"
# or control each character

# [editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# nnbsp = "␣"
# tab = "→"
# newline = "⏎"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
tab = "no_op"
S-tab = "no_op"
space.T = ":sh ls"
# space.B = ":sh echo '%{language}:%{cursor_column}'"
space.B = ':sh -c \"echo "20 * 5" | bc\"'
C-x = "toggle_comments"
C-c = "collapse_selection"

[keys.insert]
S-tab = "no_op"
C-c = "normal_mode"
C-x = "toggle_comments"

[keys.select]
tab = "no_op"
S-tab = "no_op"
# S-tab = "no_op"

