# introduce new language server
[language-server.lsp-ai]
command = "lsp-ai"

[language-server.lsp-ai.config.memory]
file_store = { }

[language-server.lsp-ai.config.models.model1]
type = "open_ai"
chat_endpoint = "https://ai.wormsoft.ru/api/gpt/chat/completions"
completions_endpoint = "https://ai.wormsoft.ru/api/gpt/chat/completions"
model =  "qwen/qwen3.5-plus"
# model =  "openai/gpt-5.4-mini"
# model =  "openai/gpt-5.2"
# auth_token_env_var_name = "OPENAI_API_KEY"
auth_token='b40c18df59b391f5b3994b21f6e4e4de2b65afda7ffc21ba19b129333ba5df1e'

[[language-server.lsp-ai.config.chat]]
trigger = "#C"
action_display_name = "Chat"
model = "model1"
system = "You are a chatbot python coding assistant. The user will ask you for assistance coding and you will do you best to answer succinctly and accurately. In your answer, remove Markdown backquotes (` or ```) around code blocks."

[language-server.lsp-ai.config.chat.parameters]
max_tokens = 64
max_context = 1024

[[language-server.lsp-ai.config.chat]]
trigger = "#CC"
action_display_name = "Chat with context"
model = "model1"

[language-server.lsp-ai.config.chat.parameters]
max_tokens = 64
max_context = 1024
system = "You are a code assistant chatbot. The user will ask you for assistance coding and you will do you best to answer succinctly and accurately given the code context:\n\n{CONTEXT}"
      

[language-server.lsp-ai.config.completion]
model = "model1"

[language-server.lsp-ai.config.completion.parameters]
max_tokens = 64
max_context = 1024

## Configure the messages per your needs


[[language-server.lsp-ai.config.completion.parameters.messages]]
role = "system"
content = "Instructions:\n- You are an AI programming assistant.\n- Given a piece of code with the cursor location marked by \"<CURSOR>\", replace \"<CURSOR>\" with the correct code or comment.\n- First, think step-by-step.\n- Describe your plan for what to build in pseudocode, written out in great detail.\n- Then output the code replacing the \"<CURSOR>\"\n- Ensure that your completion fits within the language context of the provided code snippet (e.g., Python, JavaScript, Rust).\n\nRules:\n- Only respond with code or comments.\n- Only replace \"<CURSOR>\"; do not include any previously written code.\n- Never include \"<CURSOR>\" in your response\n- If the cursor is within a comment, complete the comment meaningfully.\n- Handle ambiguous cases by providing the most contextually appropriate completion.\n- Be consistent with your responses."

# [[language-server.lsp-ai.config.completion.parameters.messages]]
# role = "user"
# content = "def greet(name):\n    print(f\"Hello, {<CURSOR>}\")"

# [[language-server.lsp-ai.config.completion.parameters.messages]]
# role = "assistant"
# content = "name"

# [[language-server.lsp-ai.config.completion.parameters.messages]]
# role = "user"
# content = "function sum(a, b) {\n    return a + <CURSOR>;\n}"

# [[language-server.lsp-ai.config.completion.parameters.messages]]
# role = "assistant"
# content = "b"

# [[language-server.lsp-ai.config.completion.parameters.messages]]
# role = "user"
# content = "fn multiply(a: i32, b: i32) -> i32 {\n    a * <CURSOR>\n}"

# [[language-server.lsp-ai.config.completion.parameters.messages]]
# role = "assistant"
# content = "b"

# [[language-server.lsp-ai.config.completion.parameters.messages]]
# role = "user"
# content = "# <CURSOR>\ndef add(a, b):\n    return a + b"

# [[language-server.lsp-ai.config.completion.parameters.messages]]
# role = "assistant"
# content = "Adds two numbers"

# [[language-server.lsp-ai.config.completion.parameters.messages]]
# role = "user"
# content = "# This function checks if a number is even\n<CURSOR>"

# [[language-server.lsp-ai.config.completion.parameters.messages]]
# role = "assistant"
# content = "def is_even(n):\n    return n % 2 == 0"

# [[language-server.lsp-ai.config.completion.parameters.messages]]
# role = "user"
# content = "{CODE}"

[language-server.hx-lsp]
# command = "target/debug/hx-lsp"
command = "hx-lsp"
# args = ["--log"] # for dev

[language-server.scls]
command = "simple-completion-language-server"

# [language-server.lsp-ai]
# args = ["--config", "/home/lion/Templates/lsp-ai.conf"]
# # args = ["--stdio", "--config", "/home/lion/Templates/lsp-ai.conf"]
# environment = { "OPENROUTER_API_KEY" = "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" }
# command = "lsp-ai"

[language-server.pylsp]
command = "pylsp"

[language-server.emmet-ls]
args = ["--stdio"]
command="emmet-ls"

# args = ["--stdio"]
# command="/home/m9y/.config/nvm/versions/node/v24.7.0/bin/vls"
# language-servers ={ command = "vue-language-server", args = ["--stdio"] }

# [language-server.vls]
# # args = ["--stdio"]
# command="vls"

[language-server.volar-vls]
command="/home/m9y/.yarn/bin/vls"
args = ["--stdio"]
 # command = "vue-language-server"

# [language-server.pylsp.config]
# formatter=false

[language-server.scls.config]
max_completion_items = 20            # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
feature_unicode_input = true         # enable "unicode input"
feature_paths = true                 # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

[[language]]
name = "python"
# language-servers = [ "scls", "lsp-ai" ]
# language-servers = [ "scls", "pylsp"]
language-servers = [ "hx-lsp", "pylsp", "lsp-ai" ]
# auto-format = false

[[language]]
name = "markdown"
language-servers = [ "hx-lsp"]

[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"

# [language.debugger]
# name = "debugpy"
# transport = "stdio"
# command = "python3"
# args = ["-m", "debugpy.adapter"]

[[language]]
name = "bash"
language-servers = [ "hx-lsp", "bash-language-server"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "rust"
language-servers = [  "hx-lsp", "rust-analyzer" ]
workspace-lsp-roots = ["fuzz"]
scope = "source.rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true

[[language]]
name = "git-commit"
language-servers = [ "hx-lsp" ]

[[language]]
name = "javascript"
file-types = ["js", "ts"]
language-servers = [ "hx-lsp", "typescript-language-server", "typescript" ]


[[language]]
name = "css"
language-servers = [ "hx-lsp" ]

[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server", "hx-lsp", "emmet-ls" ]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
# location = "/home/lion/.nvm/versions/node/v24.7.0/lib/node_modules/@vue/typescript-plugin"
location = "/home/mo/.config/nvm/versions/node/v22.20.0/lib/node_modules/@vue/language-server"
languages = ["vue"]

# [[language]]
# name = "vue"
# file-types = ["vue"]
# scope = "text.html.vue"
# roots = ["package.json"]
# injection-regex = "vue"
# language-servers = [ "scls", "emmet-ls" ]
# block-comment-tokens = { start = "//", end = "//"}

[[language]]
name = "html"
language-servers = [ "hx-lsp", "emmet-ls" ]
scope = "text.html.basic"
injection-regex = "html"
file-types = ["html", "htm", "shtml", "xhtml", "xht", "jsp", "asp", "aspx", "jshtm", "volt", "rhtml", "cshtml"]
block-comment-tokens = { start = "<!--", end = "-->" }
auto-format = true
indent = { tab-width = 2, unit = "  " }

[language.auto-pairs]
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

